### ISSUE TITLE
A brief look

### ISSUE THREAD

**Issue by akshatmittal** [visualizevalue-dev/infinity-contracts#1]
I had a brief look at the repo and here are some initial thoughts:

1. The repo is using conflicting package managers, with both `package-lock.json` and `yarn.lock` present at root, with conflicting dependencies.
2. A bunch of packages are conflicting with each other, mostly arising from the migration to `ethers@v6`.
3. Deterministic deployment is set up, but is not using a proper seed for any vanity. (Happy to generate a seed for you with a vanity `420420` address or something else, just let me know)
4. Contract contains multiple deploy scripts. It's best to use a common deploy pattern for tests and production.
5. Some unused config files.
6. Missing a bunch of types in several places.

Some initial thoughts on the contracts: (I just spent a couple minutes looking at the contracts, will do a better rundown tomorrow)

1. The libraries are less the ideal in terms of packing optimization.
2. The contracts use inconsistent revert messages.
3. Missing reentrancy protection. (although they mostly do follow CEI, so that is likely not a problem)

Kudos to you for some great things:

1. Proper NatSpec documentation. *chef's kiss*
2. Infinity metadata and generation looks amazing.

I fully intend to submit a PR to resolve some of these things tomorrow. It's a bit too late for me right now (3am) but I wanted to share some of my thoughts!

**Comment by jwahdatehagh** [comment]
Thank you so much @akshatmittal!

1. Quickly deleted the package-lock, that wasn't supposed to be there.. 
2. Thank you, will take another look as well!
3. Used a seed that resulted in an `0x008...` address in the previous version which seemed in spirit with the collection. will of course have to adjust for the next deployment. or am i misunderstanding something?

Regarding the contracts:

1. I've grown to like the libraries pattern, especially since some of my contracts grew too large for a normal contract deployment (Checks Originals)
2. You mean the `revert` in the `_send(` method? Good catch, will adjust!
3. Please triple check where you think it's required!

Thanks again, i'll add you to the authors list, feel free to adjust / edit as pleased via a PR!

**Comment by jwahdatehagh** [comment]
Re 4.) fixed in https://github.com/visualizevalue-dev/infinity-contracts/commit/f840c24058086705f5385a6dce244da8d1a7fdfa

**Comment by jwahdatehagh** [comment]
See comment in #2
